[package]
name = "tip-job"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
notion = "0.5.1"
notion-client = "0.1.9"
reqwest = "0.11.25"
serde = "1.0.197"
tokio = "1.36.0"
